/**
 * T123-IMPLEMENTAR EL EJEMPLO DEL TARRO DE ACEITUNAS USANDO UN ATRIBUTO ARRAY DE CLASE Y UN ATRIBUTO ARRAY DE INSTANCIA
 * CON 2 CONSTRUCTORES. REALIZAR PRUEBAS DEMOSTRANDO EL ORDEN DE EJECUCION DE LOS BLOQUES DE INICIALIZACION
 */
public class Principal {

    public static void main(String[] args) {
        Tarro tarro = new Tarro();
    }



}
